name: Server Deploy
on:
  push:
    branches:
      - prod
jobs:
  build:
    name: SSH Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote deploy command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/snekk/
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          yarn
          yarn server:build
          pm2 reload all --update-env
    # - name: Notify Rollbar
    #   uses: rollbar/github-deploy-action@2.1.1
    #   id: rollbar_deploy
    #   with:
    #     environment: 'production'
    #     version: ${{ github.sha }}
    #   env:
    #     ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
    #     ROLLBAR_USERNAME: snekk
