name: Server Deploy
on:
  push:
    branches:
      - prod

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Executing remote deploy command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: cd /snekk/ && ./scripts/pm2deploy.sh
